### ISSUE TITLE
Update to v3.6

### ISSUE THREAD

**Issue by toby3d** [toby3d/telegram#6]
- [ ] #1 Support text formatting in media captions
- [ ] Add test for checking nested messages in replies to the bot 
- [ ] #2 Add the new field connected_website to Message
- [ ] #3 Add the new parameter supports_streaming
